implement live stream
0chain/0proxy pull request #10
Opened 2021-07-27 14:54 UTC by cryptoDev222

Implement live stream
To test, use zboxcli for upload

2021-07-28 10:19 UTC, moldis commented on docker.local/config/0proxy.yaml
> +block_worker: https://stream.0chain.net/dns
This should not be in repo

2021-07-28 10:19 UTC, moldis commented on docker.local/Dockerfile
> +COPY ./code/go/0proxy.io/gosdk/go.mod          ./code/go/0proxy.io/gosdk/go.sum          $SRC_DIR/go/0proxy.io/gosdk/
Why do you need gosdk included?

2021-07-28 10:22 UTC, moldis commented on code/go/0proxy.io/zproxycore/handler/livestream.go
> +package handler
As I know this file is mostly copy pasted from zbox cli, hence it needs to be refactored or moved to gosdk. My comments below

2021-07-28 10:24 UTC, moldis commented on code/go/0proxy.io/zproxycore/handler/livestream.go
> +	playlist       *sdk.MediaPlaylist
Variables naming are confused, pls rename them to make it more clear, especially watoToDownload don etc

2021-07-28 10:25 UTC, moldis commented on code/go/0proxy.io/zproxycore/handler/livestream.go
> +	file, err := os.Create(localPath)
Have you tested it with multiple users opened same shared file? I guess it will ovveride stream

2021-07-28 10:25 UTC, moldis commented on code/go/0proxy.io/zproxycore/handler/livestream.go
> +	go d.autoDownload()
Methods naming are confusing, pls rename

2021-07-28 10:25 UTC, moldis commented on code/go/0proxy.io/zproxycore/handler/livestream.go
> +	go d.autoRefreshList()
How does it work if user closed streaming, it will stop autorefresh it?

2021-07-28 10:26 UTC, moldis commented on code/go/0proxy.io/zproxycore/handler/livestream.go
> +		item := <-d.waitToDownload
Same question above

2021-07-28 10:26 UTC, moldis commented on code/go/0proxy.io/zproxycore/handler/livestream.go
> +				//	buf, _ := json.Marshal(list)
Pls, clear all commets. Commets have to be only on functio header

2021-07-28 10:27 UTC, moldis commented on code/go/0proxy.io/zproxycore/handler/livestream.go
> +	//TODO: add download ts files from auth ticket
+1 comments + based on comment it will not work for auth ticket

2021-07-28 10:28 UTC, moldis commented on code/go/0proxy.io/zproxycore/handler/livestream.go
> +type SortedListResult []*sdk.ListResult
Please, refactor this block with SortedListResult. Simple operation takes to much code here and hard to read it. Also comment showing it sorting by time, but according to code it sorting by name

2021-07-28 10:28 UTC, moldis commented on code/go/0proxy.io/zproxycore/handler/livestream.go
> +	// Type          string             `json:"type"`
+1 comments cleanup

2021-07-28 10:29 UTC, moldis commented on code/go/0proxy.io/zproxycore/handler/livestream.go
> +	if r.Method != http.MethodGet {
You can put this filter to handler level

2021-07-28 10:31 UTC, moldis commented on code/go/0proxy.io/zproxycore/handler/livestream.go
> +// Download is to download a file from dStorage
Wrong comment

2021-07-28 10:32 UTC, moldis commented on code/go/0proxy.io/zproxycore/handler/livestream.go
> +		os.Exit(1)
Does it mean it will shut down whole go code? It's an API method it should just return error response

2021-07-28 10:33 UTC, moldis commented on code/go/0proxy.io/zproxycore/handler/livestream.go
> +	delay := 5
'Magic' number here, pls move to configs env

2021-07-28 10:33 UTC, moldis commented on code/go/0proxy.io/zproxycore/handler/livestream.go
> +		os.Exit(1)
+1 to comment above

2021-07-28 10:33 UTC, moldis commented on code/go/0proxy.io/zproxycore/handler/livestream.go
> +	// m3u8.Start()
+ 1 comments

2021-07-28 10:34 UTC, moldis commented on code/go/0proxy.io/zproxycore/handler/livestream.go
> +		os.Exit(1)
+1 comment above about os.Exit

2021-07-28 10:34 UTC, moldis commented on code/go/0proxy.io/zproxycore/handler/livestream.go
> +package handler
+ there is no unit-tests for this file

2021-07-28 10:36 UTC, moldis requested changes
Code refactoring and code cleanup

2021-07-28 13:45 UTC, cryptoDev222 commented on docker.local/config/0proxy.yaml
> +block_worker: https://stream.0chain.net/dns
Okay, got it.

2021-07-28 13:49 UTC, cryptoDev222 commented on docker.local/Dockerfile
> +COPY ./code/go/0proxy.io/gosdk/go.mod          ./code/go/0proxy.io/gosdk/go.sum          $SRC_DIR/go/0proxy.io/gosdk/
Because the download is not working good with newest gosdk version, so I use the dayi/main branch basically.

2021-07-28 14:03 UTC, cryptoDev222 commented on code/go/0proxy.io/zproxycore/handler/livestream.go
> +	file, err := os.Create(localPath)
The localPath is path to save m3u8 file at 0proxy, so it's override when the new stream started.

2021-07-28 14:03 UTC, cryptoDev222 commented on code/go/0proxy.io/zproxycore/handler/livestream.go
> +	go d.autoDownload()
Okay, got it.

2021-07-28 14:08 UTC, cryptoDev222 commented on code/go/0proxy.io/zproxycore/handler/livestream.go
> +				//	buf, _ := json.Marshal(list)
Okay, got it.

2021-07-28 14:08 UTC, cryptoDev222 commented on code/go/0proxy.io/zproxycore/handler/livestream.go
> +	//TODO: add download ts files from auth ticket
Okay.

2021-07-28 14:10 UTC, cryptoDev222 commented on code/go/0proxy.io/zproxycore/handler/livestream.go
> +	if r.Method != http.MethodGet {
Sure

2021-07-28 14:40 UTC, cryptoDev222 commented on code/go/0proxy.io/zproxycore/handler/livestream.go
> +type SortedListResult []*sdk.ListResult
TS files named after times.

2021-08-02 08:04 UTC, moldis commented on docker.local/Dockerfile
> +COPY ./code/go/0proxy.io/gosdk/go.mod          ./code/go/0proxy.io/gosdk/go.sum          $SRC_DIR/go/0proxy.io/gosdk/
@cryptoDev222 Then is should not be in PR here anyway

2021-09-30 02:41 UTC, cnlangzi commented
will move this feature to fix in #20

2021-09-30 02:41 UTC, closed without merging