add server_time endpoint and update script
0chain/0proxy pull request #36
Opened 2021-11-22 06:42 UTC by Rizary

fix #35

2021-11-22 06:43 UTC, Rizary commented
Endpoint information in README.md is not accurate anymore.

2021-11-24 07:43 UTC, cnlangzi requested changes

2021-11-24 07:43 UTC, cnlangzi commented on docker.local/bin/start.sh
> +docker-compose -p 0proxy -f docker.local/docker-compose.yml up
please update README.md for this change too.

2021-11-24 07:45 UTC, cnlangzi commented
please add api document README.md like https://github.com/0chain/0proxy#sync . it helps front-end team to check it instead of review code

2021-11-25 00:55 UTC, cnlangzi requested changes

2021-11-25 00:55 UTC, cnlangzi commented on README.md
> +1637754327
it is different form your code. 

{ "time": 1637754327 }

2021-11-25 03:23 UTC, cnlangzi approved these changes

2021-11-25 03:27 UTC, merged